[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "javascript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "jsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "tsx"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "json"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "jsonc"
language-servers = [ { name = "vscode-json-language-server", except-features = [ "format" ] }, "biome" ]
auto-format = true

[[language]]
name = "html"
language-servers = [ "biome" ]
auto-format = true

[[language]]
name = "svg"
scope = "source.svg"
injection-regex = "svg"
file-types = ["svg"]
language-servers = [ "biome" ]
auto-format = true
block-comment-tokens = { start = "<!--", end = "-->" }
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
"<" = ">"

[[language]]
name = "css"
language-servers = [ "biome" ]
auto-format = true
